### ISSUE TITLE
Add .hidden class

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#150]
The order field should be hidden but due to no .hidden class it is displayed.

Go to Articles > Categories.

![order-hidden](https://user-images.githubusercontent.com/368084/112574089-d86e5c00-8daa-11eb-88b8-d8b8caa93ae2.jpg)

**Comment by C-Lodder** [comment]
Thanks Sharky.
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/d70856fbb103f1e9a6666aac29664d4f21126540
