### ISSUE TITLE
Calendar is expanded by default and not possible to close

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#151]
![calendar](https://user-images.githubusercontent.com/368084/112574539-bde8b280-8dab-11eb-8601-9119b69d1090.jpg)

**Comment by C-Lodder** [comment]
Thanks Quy.
This was also related to the missing `.hidden` class, and fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/d70856fbb103f1e9a6666aac29664d4f21126540
