### ISSUE TITLE
Remove white background

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#152]
Add/Edit an article.

![bg-white](https://user-images.githubusercontent.com/368084/112656340-8a8b3f80-8e0e-11eb-861d-0bc88b92b904.jpg)

**Comment by C-Lodder** [comment]
This is caused by `bg-white` here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/tmpl/article/edit.php#L74

which actually isn't needed for Atum, so I'd suggest submitting a PR to remove that class in the Joomla repo.

**Comment by Quy** [comment]
PR submitted. https://github.com/joomla/joomla-cms/pull/32877

Thanks!
