### ISSUE TITLE
Alert Boxes are with bad z-index

### ISSUE THREAD

**Issue by uzielweb** [C-Lodder/joomla4-backend-template#209]
When upgrading the div for System Alert Message is over all other divs.
This turns impossible to click in other divs and buttons.
You can solve this usin a good z-index or display none when has no messages.

**Comment by C-Lodder** [comment]
Hi @uzielweb, I don't quite understand what you mean.
Could you provide a little more detail and a screenshot please?

**Comment by uzielweb** [comment]
When the alert message occurs in modal box, the modal wrap window is over all content and does not disappears after closing modal box.
So the content behind is not clickable when this occurs.

**Comment by uzielweb** [comment]
In the latest version of Joomla 4.0.3 this is not  occurring for now. May this was fixed by Joomla Team. I will report you when this error appear in next time.
