### ISSUE TITLE
Issue with Advanced Module Manager from regularlabs

### ISSUE THREAD

**Issue by PeterSpie** [C-Lodder/joomla4-backend-template#282]
Hello,
the  Advanced Module Manager from regularlabs breaks the back end. Because I use the free version, I don't access to the bug-reporting from this developer. 
Maybe anyone else had a way to report this issue to him?

Regards, Peter

**Comment by C-Lodder** [comment]
Hi Peter,

Issue is with `\administrator\templates\bettum\html\layouts\com_modules\joomla\form\field\modulespositionedit.php`

Please delete this file and I'll sort it out with the next update

**Comment by PeterSpie** [comment]
Hi Charlie,
yeah! working perfect now.
Sorry I can only report this issues. I am not a developer so I can not help you with this.
But I like the template very much, so when I see more bugs, I will report them here.

regards, Peter

**Comment by C-Lodder** [comment]
Fixed: https://github.com/C-Lodder/joomla4-backend-template/commit/e790dc47c656f887b3d17e29c6685c30629cdc81
