### ISSUE TITLE
Add a module posistions image on the readme.md

### ISSUE THREAD

**Issue by shoulders** [C-Lodder/joomla4-backend-template#307]
this would be just a small addition to the information for users that come to this repo but very useful. The same as ?tp=1 generates.

thanks

**Comment by C-Lodder** [comment]
Hi @shoulders,

Could do, although I didn't really see much point as the module position are the same as Joomla's Atum template.
If you do feel it would be beneficial, I'd happily accept a PR.

**Comment by shoulders** [comment]
leave it with me, i just need to get my head around Github pull requests 😄
