### ISSUE TITLE
fouc

### ISSUE THREAD

**Issue by brianteeman** [C-Lodder/joomla4-backend-template#31]
the template is really fast and light but I noticed a fouc on every component load

![fouc](https://user-images.githubusercontent.com/1296369/68971583-bd1c3580-07e1-11ea-8575-f4d601a4b3ad.gif)

**Comment by C-Lodder** [comment]
https://github.com/C-Lodder/joomla4-backend-template/commit/cc1b881b980ce955d2dca5f427d24f0275f9c2ce
