### ISSUE TITLE
The CUSTOM MENU in the MENU position overlaps with the DEFAULT MENU

### ISSUE THREAD

**Issue by studio-express** [C-Lodder/joomla4-backend-template#323]
Steps:

1. Create a _custom menu_ via the menu manager
2. Select an _alternative main menu_ in the menu preset type
3. Assign the menu module to the _munu position_

Bug:

The two menus **overlap** in MENU position (left).

![2022-09-13 16 13 54](https://user-images.githubusercontent.com/4165508/189898813-7ff1f042-7e94-4782-bbbe-fade2a1aef5f.gif)

**Comment by C-Lodder** [comment]
I've released an update which fixes this issue
