### ISSUE TITLE
Custom user menu in Menu position - no icon for the menu item

### ISSUE THREAD

**Issue by studio-express** [C-Lodder/joomla4-backend-template#324]
Steps:

1. Create a custom menu via the menu manager
2. Select an alternative main menu in the menu preset type
3. Assign the menu module to the munu position
4. Create a menu item
5. Select an icon class for the menu item

Bug:

No icon for the menu item.
Checked the classes for icons: (fas fa-object-group) or (icon-home icon-fw) – no result.
The browser console does not add an icon class to the _span_ tag.

**Comment by C-Lodder** [comment]
Thank you for reporting. I'll look into this and your other issue when I get a chance.

**Comment by C-Lodder** [comment]
I've released an update which fixes this issue
