### ISSUE TITLE
Support for Phocatop Menu

### ISSUE THREAD

**Issue by patrickvalmont** [C-Lodder/joomla4-backend-template#355]
Hi guys, I tested this today and it's an amazing update over atum. Nice job. However, would be great if this had support for PhocaTop menu. Can this be made possible ?

**Comment by C-Lodder** [comment]
Hi patrickvalmont, the Bettum template already supports a top menu. You simply need to enable it in the template settings.

![image](https://user-images.githubusercontent.com/2019801/222515522-b0e6c395-3524-477a-877d-824fbcd032cf.png)

**Comment by patrickvalmont** [comment]
> Hi patrickvalmont, the Bettum template already supports a top menu. You simply need to enable it in the template settings.
> 
> ![image](https://user-images.githubusercontent.com/2019801/222515522-b0e6c395-3524-477a-877d-824fbcd032cf.png)

Hi Support, ah, I see now. Got it, thanks!!
