### ISSUE TITLE
Adding padding to custom module

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#50]
![padding](https://user-images.githubusercontent.com/368084/83088210-f1ea2e80-a047-11ea-866b-5eda5e76e132.png)

**Comment by C-Lodder** [comment]
Thank you.

Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/1390cf81c341f2f4d0b6d37401240f4506c6f337

Will be releasing an update today
