### ISSUE TITLE
Change cursor of drag/drop icon

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#52]
The mouse cursor does not change on hover of the module drag/drop icon. It should be a hand cursor or the drag/drop icon.

**Comment by C-Lodder** [comment]
Thanks. I'll fix this tomorrow

**Comment by C-Lodder** [comment]
Fixed: https://github.com/C-Lodder/joomla4-backend-template/commit/d41533c46becd00e73a29e0d260eb0f71afc4202
