### ISSUE TITLE
Side navigation headers not obvious

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#53]
Headers and links look the same so mistakenly will click on headers.

![global-configuration](https://user-images.githubusercontent.com/368084/83155735-665bb680-a0b6-11ea-918a-6482334a4b52.png)

**Comment by C-Lodder** [comment]
Thanks. I'll fix this tomorrow

**Comment by C-Lodder** [comment]
Fixed: https://github.com/C-Lodder/joomla4-backend-template/commit/1d6afe7d98cca75ff164637d97f6e1ad0c0a13e3
