### ISSUE TITLE
Make sidebar not clickable in edit mode

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#55]
Edit an article.
Clicking Home Dashboard makes the article checked out.
Maybe make all links in sidebar be non-clickable in edit mode.

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/bd099dd18ffe2219c0204a4c1748acb17545ab76

Thanks for reporting
