### ISSUE TITLE
Heading in dropdown menu not visible

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#58]
![heading](https://user-images.githubusercontent.com/368084/83693183-6b36d380-a5aa-11ea-9e79-dcf076612e24.png)

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/283a366a5aeff3d1bc26604e2ea4bf6abb01f91f and will be in the next update. Thanks
