### ISSUE TITLE
Make spinning logo crisp when installing sample data

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#60]
![logo-install](https://user-images.githubusercontent.com/368084/84420971-b9159200-abcf-11ea-8f87-14147c03d087.png)

**Comment by C-Lodder** [comment]
Happy to improve this in Bettum, but isn't this pixelated logo also present in Atum?

**Comment by Quy** [comment]
Probably but more noticeable against the dark background.

**Comment by C-Lodder** [comment]
Removed loading icon as it's already using progress bars.
Fixed background for progress bars too

https://github.com/C-Lodder/joomla4-backend-template/commit/f794b79fe3a71713df3b351796aa57b0ff1c27f6
