### ISSUE TITLE
Style sidebar title

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#62]
![sidebar-title](https://user-images.githubusercontent.com/368084/84704845-4e39c300-af0f-11ea-9c25-92df6faa0486.png)

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/a6e87c1d607ac4d99b3fa582959d613a679fab65

Thaank you
