### ISSUE TITLE
Reduce width of password meter

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#64]
![password-meter](https://user-images.githubusercontent.com/368084/84787951-6c510300-afa3-11ea-88ec-5f0e2c462397.png)

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/9ee3bd914ce8c04040fc60691e654a6d35c23aa7

Thanks
