### ISSUE TITLE
Missing TPL_BETTUM_ALTTEXT_SITE_LOGO_LABEL

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#68]
`<img src="/joomla-cms-4.0-dev/administrator/templates/bettum/images/logo-sm.svg" alt="TPL_BETTUM_ALTTEXT_SITE_LOGO_LABEL">`

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/8ca976a8c82b7db215c9e57fd68a05192527236c
