### ISSUE TITLE
How to recognize Bettum, how to recognize that left menu is not active?

### ISSUE THREAD

**Issue by PhocaCz** [C-Lodder/joomla4-backend-template#69]
Hi,

is there a way how to recognize that:

- Bettum template with dark background is active (CSS)?
- Bettum template without left menu is active (PHP)?

Let's say, I have an extension which includes some styles for white background. It will be easy to add even some style for black background template when e.g. the body or any other part will include such information. For example:

```<body class="admin com_... view-... layout-default task-display layout-style-dark" ...```

Similar question is, if there is some way to recognize that the left menu is disabled. In such case the extension can load its own menu: JHtmlSidebar::render(); instead.

Of course, these are maybe much more questions on Joomla! core developers, but maybe there can be some way how to solve it in template.

Regarding the left menu, I would say, that the only one option is just loading template parameters in extension. But regarding the black background, maybe there can be another way based on class (so CSS of extension can be ready for this)

Thank you, Jan

**Comment by C-Lodder** [comment]
1. Right not, Bettum is always dark, so there's no way to detect if Bettum is dark. Once I add a light theme, I'll add a class to the `<body>` tag, probably `bettum-dark` and `bettum-light`.

2. You can simply get the parameter from the template, like so:

```
use Joomla\CMS\Factory;

$sidebar = Factory::getApplication()->getTemplate(true)->params->get('menu', 1) ? true : false;

if ($sidebar)
{
    // has sidebar
}
else
{
    // has no sidebar
}
```

Or if you actually want to detect whether or not the menu items are active/disabled:

```
$hideLinks = Factory::getApplication()->input->getBool('hidemainmenu');
```

**Comment by PhocaCz** [comment]
Hi, thank you for your answers

1. For now I mean rather a detecting whether Bettum or Atum is loaded (per CSS way). If there is some class in HTML output which will allow me to detect if the Bettum template is active or not. I can assume that Bettum is dark, but I need to use a class or ID to find out that Bettum is active (and not Atum).

2. ```$sidebar = Factory::getApplication()->getTemplate(true)->params->get('menu', 1) ? true : false;```

Great, that's what I'm looking for.

![left menu active](https://i.imgur.com/qvPPAax.png)

Thank you, Jan

**Comment by C-Lodder** [comment]
I will add a `tpl-bettum` class to the `<body>` element in the next commit.

**Comment by PhocaCz** [comment]
Great. Thank you.

**Comment by C-Lodder** [comment]
Class added in https://github.com/C-Lodder/joomla4-backend-template/commit/e384c575a87c455941cca02da90f8b5a5f53dafa
