### ISSUE TITLE
Dropdown not full width

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#71]
Edit an article.
Click the x icon.
Assign a different category.
Save article.
Edit the same article.

![category-dropdown](https://user-images.githubusercontent.com/368084/85355246-098aca80-b4c1-11ea-856c-cd085401df0a.png)

**Comment by C-Lodder** [comment]
Thanks.

This should be fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/63d9207d1f4befdd577f0ec227a7a7c101f4178a
