### ISSUE TITLE
Add Multilingual Status title attribute to icon

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#86]
The other icons have the title attribute except for the `Multilingual Status` icon. 

![multilanguage-icon](https://user-images.githubusercontent.com/368084/92263214-1b112b00-ee91-11ea-9c7c-e914d8e698a5.png)

**Comment by C-Lodder** [comment]
Thanks @Quy.
Fix here: https://github.com/C-Lodder/joomla4-backend-template/commit/a81d68e21dc2999286f4f186bfbf17437031691e
