### ISSUE TITLE
Alert danger styling

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#87]
![alert](https://user-images.githubusercontent.com/368084/92273923-24a28f00-eea1-11ea-8c2e-ead339960ea2.png)

Create a new article.
Leave title blank.
Click Save button.

**Comment by C-Lodder** [comment]
Seem to have been caused by https://github.com/joomla/joomla-cms/pull/30294
Will look into this another day

**Comment by C-Lodder** [comment]
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/25c6bf0db06f291c45355d750589846a94c057f2
