### ISSUE TITLE
Mass Mail Users alert

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#88]
![mass-mail=users](https://user-images.githubusercontent.com/368084/92274138-82cf7200-eea1-11ea-80d6-eb229332833e.png)

Click Mass Mail Users
Leave fields blank
Click Send Email button
See empty `<button></button>` markup.

**Comment by C-Lodder** [comment]
Thanks.
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/594a14e8849bc36af8c6f3afff81af1eebd3d021
